In [1]:
import numpy as np

## **Matriz 2x5**

In [2]:
MD = np.array([[1,2,3,4,5],[6,7,8,9,10]])   

In [3]:
print("{}".format(MD))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


## **Matriz 3x5**

In [4]:
MT = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [5]:
print("{}".format(MT))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


## **Matriz Quadrada**

In [6]:
MQ= np.array([[1,2,3],[4,5,6],[7,8,9]])

In [7]:
print("{}".format(MQ))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## **Matriz Identidade**

In [8]:
I = np.eye(4)

In [9]:
print("{}".format(I))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# **Operações com Matrizes**

## **Soma Elemento a Elemento**

In [10]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[-1,0,1],[0,1,1],[4,4,4]])

In [11]:
S = A+B

In [12]:
print("{}".format(S))

[[ 0  2  4]
 [ 4  6  7]
 [11 12 13]]


## **Soma Linha**

In [ ]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
A.sum(axis = 1)

array([ 6, 15, 24])

## **Soma Coluna**

In [14]:
A.sum(axis = 0)

array([12, 15, 18])

## **Subtração de elemento a elemento**

In [15]:
SB1=A-B

In [ ]:
print("{}".format(SB1))

[[2 2 2]
 [4 4 5]
 [3 4 5]]


In [16]:
SB2=B-A

In [17]:
print("{}".format(SB2))

[[-2 -2 -2]
 [-4 -4 -5]
 [-3 -4 -5]]


### **Multiplicação por Escalar**

In [ ]:
k=2
A*k

array([[ 2,  4, 14],
       [ 6, 12, 14],
       [16, 18,  0]])

## **Multiplicação elemento a elemento**

In [18]:
A*B

array([[-1,  0,  3],
       [ 0,  5,  6],
       [28, 32, 36]])

## **Transposta**

In [19]:
AT = A.T

In [20]:
print("{}".format(AT))

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
AT.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## **Potência**

In [21]:
A**5

array([[    1,    32,   243],
       [ 1024,  3125,  7776],
       [16807, 32768, 59049]], dtype=int32)

## **As operações acima podem ser resolvidas utilizando o numpy**

### **Soma de elemento a elemento**

In [22]:
np.add(A,B, dtype = np.float16)

array([[ 0.,  2.,  4.],
       [ 4.,  6.,  7.],
       [11., 12., 13.]], dtype=float16)

### **Subtração de elemento a elemento**

In [23]:
np.subtract(A,B, dtype = np.int32)

array([[2, 2, 2],
       [4, 4, 5],
       [3, 4, 5]])

### **Multiplicação de elemento a elemento**

In [24]:
np.multiply(A,B, dtype = float)

array([[-1.,  0.,  3.],
       [ 0.,  5.,  6.],
       [28., 32., 36.]])

### **Transposta**

In [25]:
np.transpose(A)

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [26]:
A = np.array([[1,2,3],[4,5,6]])
B = np.array([[1],[1],[1]])

### **Multiplicação matricial linha x coluna**

In [27]:
np.matmul(A,B)

array([[ 6],
       [15]])

Observe que o contrário não está definido, devido ao número de linhas e colunas

In [28]:
np.matmul(B,A)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 1)

Outra forma de realizar multiplicação matricial linha x coluna

In [29]:
np.dot(A,B)

array([[ 6],
       [15]])

### **Elevando os elementos da matriz a uma potência n**



Para inteiros positivos n, a potência é calculada por quadraturas e multiplicações de matrizes repetidas.

Se n == 0, a matriz identidade da mesma forma que M é retornada.

Se n < 0, o inverso é calculado e então elevado ao abs(n).

In [30]:
A = np.array([[1,2,7],[3,6,7],[8,9,0]])

In [31]:
np.linalg.matrix_power(A,5)

array([[123235, 185759, 175273],
       [205065, 300027, 255535],
       [221333, 307524, 210945]])

### **Ler matriz do teclado**

Primeiro indicar o número de linhas e colunas

In [32]:
# recebe a quantidade de linhas da matriz
linha = int(input("Informe quantas linhas tem sua matriz: "))
# recebe a quantidade de colunas da matriz
coluna = int(input("Informe quantas colunas tem sua matriz: "))

Iniciando uma matriz de números reais com linhas e colunas definidas

In [33]:
A = np.empty([linha,coluna], dtype = float)

Recebe os elementos da matriz digitados pelo teclado

In [ ]:
for i in range(0, linha):
    for j in range(0, coluna):
        A[i][j] = float(input("Insira o elemento [{}][{}] da matriz: ".format(i + 1,j + 1)))

Insira o elemento [1][1] da matriz: 2
Insira o elemento [1][2] da matriz: 4
Insira o elemento [2][1] da matriz: 5
Insira o elemento [2][2] da matriz: 6


Imprime na tela a matriz original

In [34]:
print("\n\nA matriz digitada é:\n\n{}\n\n".format(A))



A matriz digitada é:

[[1.27385046e-311 1.27381328e-311 0.00000000e+000 6.95223623e-310
  2.71736105e-322 1.27398430e-311 1.27398430e-311 1.27398428e-311
  1.27398430e-311 1.27398430e-311 1.27398428e-311 1.27398428e-311]
 [1.27398430e-311 1.27398430e-311 1.27398430e-311 1.27398430e-311
  1.27398430e-311 1.27398428e-311 1.27398430e-311 1.27398428e-311
  1.27398428e-311 1.27398430e-311 1.27398428e-311 1.27398430e-311]
 [1.27398430e-311 1.27398428e-311 1.27398430e-311 1.27398428e-311
  1.27398428e-311 1.27398430e-311 1.27398430e-311 1.27398428e-311
  1.27398430e-311 1.27398428e-311 1.27398430e-311 1.27398430e-311]
 [1.27398430e-311 1.27398430e-311 1.27398430e-311 1.27398428e-311
  1.27398430e-311 1.27398430e-311 1.27398430e-311 1.27398430e-311
  1.27398430e-311 1.27398430e-311 1.27398430e-311 1.27398430e-311]
 [1.27398428e-311 1.27398428e-311 1.27398428e-311 1.27398430e-311
  1.27398428e-311 1.27398430e-311 1.27398430e-311 1.27398430e-311
  1.27398430e-311 1.27398430e-311 1.27398430e-31